/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import sun.security.x509.OtherName;

import java.util.HashSet;

public class Library {



    public boolean someLibraryMethod() {


       


        return true;



    }
}
